# Generated by Django 3.2.3 on 2021-06-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_nota_stock_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='stock_producto',
        ),
    ]
