# Generated by Django 3.2.3 on 2021-06-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_alter_nota_fecha_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='fecha_limite',
            field=models.DurationField(default=0, verbose_name='Fecha Limite'),
        ),
    ]
